apiVersion: v1
kind: Service
metadata:
  name: service-b-service
  namespace: service-b-ns
spec:
  selector:
    app: service-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP
