name: Deploy Services to Kubernetes

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        run: |

          docker build --no-cache -t felixjayamuni/service-a:latest -f ./service-a/Dockerfile ./service-a
          docker push felixjayamuni/service-a:latest

          docker build --no-cache -t felixjayamuni/service-b:latest -f ./service-b/Dockerfile ./service-b
          docker push felixjayamuni/service-b:latest

      # - name: Update Kubernetes manifests with new image
      #   run: |
      #     sed -i "s|felixjayamuni/service-a:latest|felixjayamuni/service-a:latest|g" k8s/service-a-deployment.yml
      #     sed -i "s|felixjayamuni/service-b:latest|felixjayamuni/service-b:latest|g" k8s/service-b-deployment.yml

      # - name: Commit and push updated manifests
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git config --global user.name "GitHub Actions"
      #     git add k8s/service-a-deployment.yml k8s/service-b-deployment.yml
      #     git commit -m "Updated images to latest"
      #     git push

      # - name: Set up kubectl
      #   uses: azure/setup-kubectl@v3

      # - name: Configure Kubeconfig
      #   run: |
      #     echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      # - name: Deploy to Kubernetes
      #   run: |
      #     kubectl apply -f k8s/service-a-deployment.yml
      #     kubectl apply -f k8s/service-a-service.yml
      #     kubectl apply -f k8s/service-b-deployment.yml
      #     kubectl apply -f k8s/service-b-service.yml
